### PR TITLE
edits to the first 3 bullets in sec 4.1

### PR DESCRIPTION
**Pull request by jablazek**
@rmandelb @drphilmarshall : I made a few edits to the first three bullet points for readability. I also added an explanatory sentence to justify the repetition of galaxy-galaxy and galaxy-shear. There is a commented out bullet point that I added for shear-shear, but Rachel's point that shear-shear has fewer additional applications is a good one.

### CODE REVIEW

**Comment by jablazek** [comment]
Also, the statement "diagnostic of the underlying cosmology" for galaxy-shear is vague. I wanted to edit this, but I wasn't sure what was meant here beyond the standard 3x2 or 2x2 information. Perhaps a shear ratio test?

**Comment by rmandelb** [comment]
Looking at the paper that is referenced there (Choi et al 2012), it's not really using info beyond 3x2pt, so it seems redundant in light of the more recent 3x2pt papers.  I think it's not necessary to keep; do you want to edit this further?

**Review by drphilmarshall — APPROVED** [review]
Thanks for these, @jablazek!

**Comment by drphilmarshall** [comment]
I commented out the Choi et al reference, and will merge Jonathan's wording in now.

**Pull request merged**
