### PR TITLE
Modified supernova cosmology section

### PR DESCRIPTION
**Pull request by rbiswas4**
- Agreed on with @reneehlozek  before hand
- Added a point about the SN science being strongly tied to cadence
	modified:   science.tex

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Great stuff @rbiswas4 , thank you! Can you please add `bbl` format bibitems to `lsst.tex`, following the blank `[()]{}` formatting of the rest of the bibliography? You should also add your name and affiliation to the author list. Thanks!

**Comment by rbiswas4** [comment]
Done.

**Review by drphilmarshall — APPROVED** [review]
Excellent, thanks Rahul!

**Comment by rmandelb** [comment]
I just noticed this wasn't merged in before I made my branch.  Do you want to merge the updated 2017-DESC-update post-merge into my branch, or want me to do it (and handle the inevitable conflicts)?

**Comment by drphilmarshall** [comment]
@rmandelb I just merged it into your branch. Let me double check with @rbiswas4 : the main survey should yield 400k SNe in total (not per year) over an area of 18,000 sq deg (not 1800 sq deg), correct?

**Comment by rbiswas4** [comment]
> I just merged it into your branch. Let me double check with @rbiswas4 : the main survey should yield 400k SNe in total (not per year) over an area of 18,000 sq deg (not 1800 sq deg), correct?

@drphilmarshall @rmandelb Correct. Sorry about the typo on 18000 sq deg. The 400k SNe in ten years matches what was sent for the requirements.

**Comment by drphilmarshall** [comment]
Great, thanks. This is one of the reasons why Fig 22 needs some caveats in
the text. ("Assumptions from Zhan et al 2008", etc)

**Pull request merged**
